version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15
    container_name: gym_postgres
    restart: always
    environment:
      POSTGRES_USER: user_academia
      POSTGRES_PASSWORD: academia123
      POSTGRES_DB: gym_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_academia -d gym_db"]
      interval: 5s
      timeout: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Serviço da sua API
  api:
    build: ./backend
    container_name: gym_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      # IMPORTANTE: No Docker, o host do banco não é 'localhost', é o nome do serviço 'db'
      DATABASE_URL: "postgresql://user_academia:academia123@db:5432/gym_db?schema=public"
    depends_on:
        db:
          condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy && npx prisma db seed && npm run dev"

volumes:
  pgdata: